apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-pipeline-test-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-pipeline-test-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: azure-pipeline-test-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-pipeline-test-front
        image: acrtest10001.azurecr.io/pipeline-test-front:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: azure-pipeline-test-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-pipeline-test-front