# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the workflow will run
on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: tag number
        run: echo ${{ github.event.release.tag_name }}

